baseURL = "https://www.sunmiya.com"
languageCode = "ko-KR"
title = "Sunmi's Website"
theme = "KeepIt"
copyright = "2019 Sunmi Kang"
enableEmoji = true
enableRobotsTXT = true
defaultContentLanguage = "kr"
Paginate = 10
preserveTaxonomyNames = true
#googleAnalytics = "UA-140141781-1"
pygmentsUseClasses = true
pygmentsCodefences = true
disqusShortname = "darongE"


[blackfriday]
  hrefTargetBlank = true

[author]
  name = "sunmi"

  [params.publisher]
    name = "sunmi"

  [params.publisher.logo]
    url = "images/logo.png"
    width = 127
    height = 40

  [params.logo]
    url = "images/logo.png"
    width = 127
    height = 40

  [params.image]
    url = "images/cover.png"
    width = 800
    height = 600

[Permalinks]
  posts = "/posts/:slug"
  code = "/go/:filename"

  [menu]
    [[menu.main]]
      name = "Blog"
      url = "/posts/"
      weight = 1
    [[menu.main]]
      name = "Categories"
      url = "/categories/"
      weight = 2
    [[menu.main]]
      name = "About"
      url = "/about/"
      weight = 3

    [[menu.main]]
      name = "Memo"
      url = "/Memo"
      weight = 4

[params]
  author = "Sunmi Kang"
  subtitle = "developer & volunteer"
  subtitle_additional = "C, C++, Swift, HTML"
  description = "iOS developer"
  socialShare = true

[params.gravatar]
    email = "sm.kang@sunmiya.com"

[params.social]
  Github = "sunmiya5"
  Email = "sm.kang@sunmiya.com"


[params.share]
  Twitter = true
  Linkedin = true
  Reddit = true
  HackerNews = true
  Facebook = true
