baseURL = "https://www.sunmiya.com"
languageCode = "ko-KR"
title = "Sunmi's Website"
theme = "KeepIt"
copyright = "2019 Sunmi Kang"
enableEmoji = true
enableRobotsTXT = true
defaultContentLanguage = "en"
Paginate = 10
preserveTaxonomyNames = true
pygmentsUseClasses = true
pygmentsCodefences = true
googleAnalytics = "UA-152728974-1"

[blackfriday]
  hrefTargetBlank = true

[author]
  name = "sunmi"

  [params.publisher]
    name = "sunmi"

    [params.publisher.logo]
      url = "logo.png"
      width = 127
      height = 40

  [params.logo]
    url = "/logo.png"
    width = 127
    height = 40

  [params.image]
    url = "cover.png"
    width = 800
    height = 600

[Permalinks]
  posts = "/posts/:slug"
  code = "/go/:filename"

  [menu]
    [[menu.main]]
      name = "Blog"
      url = "/posts/"
      weight = 1
    [[menu.main]]
      name = "Categories"
      url = "/categories/"
      weight = 2
    [[menu.main]]
      name = "About"
      url = "/about"
      weight = 3

[params]
  author = "Sunmi Kang"
  subtitle = "Junior iOS developer"
  subtitle_additional = "C, C++, Swift, Objective-C"
  description = "iOS developer"
  socialShare = true

[params.gravatar]
    email = "cutysunmi@gmail.com"

[params.social]
  Github = "sunmiya5"
  Twitter = "oddukgi"
  Email = "sm.kang@sunmiya.com"

[params.share]
  Twitter = true
  Linkedin = true
  Reddit = true
  HackerNews = true
  Facebook = true

[params.utterances]
  owner = "sunmiya5"
  repo = "hugo-comment"
  issueTerm = "pathname"
  theme = "github-light"

  [languages]
  [languages.en]
    lang = "en"
    languageName = "English"
    weight = 1
