[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.59.1"
  HUGO_ENABLEGITINFO = "true"
  
[context.production.environment]
  HUGO_ENV = "production hugo --gc --minify"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.59.1"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.next.environment]
  HUGO_ENABLEGITINFO = "true"
